### PR TITLE
Replaces tabs with spaces and remove some empty lines

### PR DESCRIPTION
**Pull request by dannywillems**
I suppose spaces it's the convention. It's so horrible to see different coding conventions when you try to understand in deep how Eliom works.

The same work must be done in other ocsigen projects. I saw tabs in some ml files in jsoo.

I didn't check for empty lines.

### CODE REVIEW

**Comment by Drup** [comment]
I'm surprised, didn't we normalized with ocp-indent not-so-long ago ?

**Comment by dannywillems** [comment]
Some tabs was there since several years (2012-2013).

**Comment by vasilisp** [comment]
@dannywillems, I know that tabs are annoying, but fixing them all at once would mess up `git blame`.
`git blame` is invaluable; looking at the associated commits has helped me quite a few times understand why things are the way they are :).

I personally re-indent when making major changes to a module, but just accept the previous possibly-ugly style otherwise.

**Comment by Drup** [comment]
@vasilisp `git log -L linestart,lineend:foo.ml` ? You get the whole history that way, which is much better anyway ...

**Comment by dannywillems** [comment]
I agree that `git blame` is invaluable and since I know it, I use it a lot. The problem with doing the style migration only when there is major changes is not a good solution because maybe it will never be done.

Both solutions are ok for me.

**Pull request merged**
