### PR TITLE
Update for new-style TyXML wrapping

### PR DESCRIPTION
**Pull request by vasilisp**
This brings Eliom up-to-speed with the new-style wrapping available in current TyXML master. See ocsigen/tyxml#58 for the TyXML side of the story. This PR presupposes ocsigen/js_of_ocaml#348.

### CODE REVIEW

**Comment by Drup** [comment]
You missed some functor application, it seems. :+1: otherwise.

**Comment by vasilisp** [comment]
Are you referring to the Jenkins output? That's because of JSOO. The JSOO master doesn't compile against TyXML master, and I didn't want to pin a very ephemeral branch.

**Comment by vasilisp** [comment]
A slightly annoying side-effect is that we now get error messages with types like `string Eliom_content.Html5.F.wrap`, which is unnecessarily complicated. Maybe TyXML could provide versions of the signature functors that don't expose wrap and such?

**Comment by Drup** [comment]
That was already the case before. I prefer to tell everyone to use `-short-path`.

**Pull request merged**
