### PR TITLE
Eliom_service and Eliom_registration adjustments

### LINKED ISSUE #200: Deprecate pa_include and remove the sigs directory
Apologies if this has been discussed before.

I wonder whether we really need `pa_include` and the `sigs` directory. We can define signatures and use standard features of the module language to include them. Am I missing something?

`sigs` is not even properly integrated into the build system.

Now (during the transition to PPX) is the right time to do it. We will be better off without a `ppx_include` preprocessor. Objections?

### LINKED ISSUE #285: Service registered by Eliom_registration.App breaks co-located apps
`Eliom_registration.App` [registers a service](https://github.com/ocsigen/eliom/blob/master/src/lib/eliom_registration.server.ml#L2210) for accessing the application's global data. This is to enable global injections in mobile apps. Currently, this is a GET service in a hard-coded location. If the Ocsigenserver runs with multiple Eliom apps (e.g., as is the case for the testsuite), we try to register multiple services on the same URL (and clearly fail).

We will have to make the URL configurable, or at least make the service optional.Unfortunately, this will be a breaking change requiring a one-line modification in all existing Eliom applications.

### PR DESCRIPTION
**Pull request by vasilisp**
The PR contains a few adjustments related to services and registration. They are grouped to ease the transition for the users of `master`.

### GADT service API

The `Meth` and `Id` submodules have gone away to make the constructors available directly under `Eliom_service` (see #294). We could keep the submodules and re-export, but I see no concrete use for them.

The `~ret` argument no longer exists. `Eliom_service.create` handles the standard case, the other cases (mostly for internal use) being available as `Eliom_service.create_{unsafe,ocaml}`. This eases our work with the documentation. The code duplication needed is basically only in the signature.

External services are now handled via a `meth` constructor.

The `Eliom_service_types` module is replaced by `Eliom_service_sigs.TYPES`.

### Global data service

It is now optional. Fixes #285.

### `Eliom_registration` signatures reorganized

Fixes #200.

### CODE REVIEW

**Comment by Drup** [comment]
I still think we should keep the submodules. The API is nicer with namespaces like that, and it means we can add new convenience functions.

**Comment by vasilisp** [comment]
I disagree :).

The constructors are the only part of the API that is interesting to users, and it is better (as per #294) if they are available under `Eliom_service`. Why provide redirection if it is the `Eliom_service` names are the ones that we really want?

There is very little that we can add. These types have a very specific role (specifying the service parameters), and they are basically feature-complete.

**Comment by Drup** [comment]
```ocaml
type id = ...

(* At the bottom of the file *)

module Id : sig
  type t = id = ...
  val untype : ...
end
```

The user doesn't have to look inside it and the various functions are not spilled inside `Eliom_registration`, but it's still properly grouped and documented.

**Comment by vasilisp** [comment]
So, a module to group `id` with a single (and trivial) function that doesn't even need to be documented, because it only exists to avoid an `Obj.magic` [in `Eliom_registration`](https://github.com/ocsigen/eliom/blob/service/src/lib/eliom_registration.server.ml#L984)? Come on, let's not exaggerate :).

**Comment by Drup** [comment]
I think we're not going to agree, so I'll let you do it and rant when we need to add new functions that are also going to end in `_id`. :p

**Pull request merged**
