### PR TITLE
fix tiny bug leading to wrong and confusing error messages

### PR DESCRIPTION
**Pull request by jrochel**

### CODE REVIEW

**Comment by vasilisp** [comment]
Can you provide an example of a wrong message? It seems to me that these options are also meant for the `eliom` tag, not just for the `eliommodule` tag`. If we have to pick one of the two for the error messages, I would go with `eliom`.

**Comment by vouillon** [comment]
Indeed, these options are meant for both tags. So, the right fix would be to pass the tag name around.

**Comment by jrochel** [comment]
Better?

**Comment by vasilisp** [comment]
I think it's OK now, merging. Thanks!

**Pull request merged**
