### PR TITLE
Many changes aiming at reducing the size of request data

### PR DESCRIPTION
**Pull request by vouillon**

### CODE REVIEW

**Comment by Drup** [comment]
I was looking at the client/server syntax "runtime" last week, and I was making myself familiar with it before doing a big cleanup. This is very welcome, I don't have to do the clean up anymore! :D

Give me tomorrow to look at it in more details, so that I can convince myself we are not breaking anything (especially the revised implementation of client values). 

Please add some comments for implementation decisions.

**Comment by Drup** [comment]
@vouillon Did you measured the improvements ? Can you give us an idea ?

**Comment by vouillon** [comment]
For the Besport landing page, the uncompressed size of the request data goes from 130k to 78k (40% lower), and the compressed size from 24755 bytes down to 17059 bytes (30% lower).

**Comment by vouillon** [comment]
I added some comments.

**Comment by Drup** [comment]
@vouillon You are using bytes apparently, which doesn't exist in old ocaml. We will need to use base-bytes and modify this a bit.

**Pull request merged**
