### PR TITLE
Use the ppx template by default

### PR DESCRIPTION
**Pull request by Drup**
Here we go. :)

### CODE REVIEW

**Comment by vasilisp** [comment]
Shouldn't `basic` refer to what is now `basic.ppx`? With a `basic.camlp4` and a possible alias between `basic` ~ `basic.ppx`.

(Details, I am happy enough if PPX is the default and what we promote, no matter what the names are.)

**Comment by Drup** [comment]
I'm ok with renaming `basic` to `basic.camlp4`. I don't feel the need for an alias.

**Comment by vasilisp** [comment]
Good, with `basic.ppx` and `basic.camlp4` there is no room for confusion about what syntax is supported.

**Comment by Drup** [comment]
@vasilisp Done.

**Pull request merged**
