### PR TITLE
Add comment to install ocsipersist in Makefile.options.

### PR DESCRIPTION
**Pull request by dannywillems**
@vasilisp Merged too fast :).

I hesitated to add it as OPAM dependency.

### CODE REVIEW

**Comment by vasilisp** [comment]
Not really :). We are still using the `ocsipersist` distributed with `ocsigenserver`. The separate package is not in OPAM, and does not even include the recently-developed Posgres backend.

**Comment by dannywillems** [comment]
@balat asked me to add `ocsipersist` in the OPAM repository. It's plan to switch to the `ocsipersist` not distributed with `ocsigenserver`

**Comment by vasilisp** [comment]
@dannywillems I am glad that you are doing this. But before we update the documentation, we need to put all the latest code in the Ocsipersist repo, update the build systems everywhere needed, update all OPAM files, and make sure everything plays nicely together.

**Comment by dannywillems** [comment]
@vasilisp (I edited my last comment. The last sentence was a question, not an affirmation.).
Hum, ok. So do I wait to add it?

**Comment by vasilisp** [comment]
@dannywillems yes, it is planned. Somebody has to step up and prioritize this task, and of course that somebody could be you if you are motivated :).

The comment would be misleading without a properly-released `ocsipersist`, so I would say wait.

**Comment by dannywillems** [comment]
@vasilisp Ahha, it's not about motivation, but about time :D.

**Pull request closed without merging**
